Elide 5.x Async API documentation
yahoo/elide-doc pull request #108
Opened 2020-04-09 18:11 UTC by moizarafat

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-09-15 22:10 UTC, aklish requested changes

2020-09-15 22:10 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +API responses can be slowed down due to multiple reasons. The most common reasons for slowness but not limited to can be complex computational logic or heavy load on the backend database or the API t
Some grammar issues here. 

I would reword:

"Elide APIs are designed for synchronous request and response behavior.  The time allowed to service a synchronous response can be limited by proxy servers and gateways.   Analytic queries can often take longer than these limits and result in a server timeout.  Elide's asynchronous API decouples the submission of a request and the delivery the response into separate client calls.  Some of the features available are:"

2020-09-15 22:10 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +* Each Elide instance runs a background process which is responsible for running the query in the background and posting the results in the database.
Reword: "Queries are run in a background thread that posts the results into a persistence store."

2020-09-15 22:10 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +* Each Elide instance runs a background process which is responsible for running the query in the background and posting the results in the database.
We should also add features for:
 - async after
 - CSV downloads
 - embedded or downloadable results

2020-09-15 22:10 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +The name of the submitter principal is associated with each query submission. The result and status of the query are only accessible to the principal that submitted the query request. If principal wa
I would simplify and says something like:

"Elide async query models have a simple permission model:  Only the principal which submitted a query is allowed to retrieve its status or results.  "

2020-09-15 22:10 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +By default the async API is disabled. The entity models needed to support the Async API are built-in. Before we enable the Async API, we need to create the schema in the database for the async models
Reword to:

"By default the async API is disabled.  The entity models needed to support the Async API are JPA models that are mapped to a specific database schema.  This schema must be created in your target database.   You can refer to [demo-schema](https://github.com/yahoo/elide-spring-boot-example/blob/master/src/main/resources/db/changelog/changelog.xml) for an example using liquibase. Feel free to modify the query/result column sizes per your needs."

2020-09-15 22:11 UTC, aklish commented
The requests and responses need to be updated to reflect the latest code as well.

2020-09-15 22:24 UTC, moizarafat commented
Update Readme to point to elide documentation.

2020-10-30 18:23 UTC, aklish requested changes

2020-10-30 18:23 UTC, aklish commented on _data/snippets/v5/async-api-additional-config.yml
> +  - Elide Standalone
Can we reorder these so spring comes first?

2020-10-30 18:23 UTC, aklish commented on _data/snippets/v5/async-api-additional-config.yml
> +          * Polling interval to identify async queries that should be canceled.
I don't understand what this means exactly.  I would think users would cancel queries.  This needs more explanation.

2020-10-30 18:23 UTC, aklish commented on _data/snippets/v5/async-api-dao-disabled.yml
> +  - Elide Standalone
Reorder them.

2020-10-30 18:23 UTC, aklish commented on _data/snippets/v5/async-api-enable.yml
> +  - Elide Standalone
Reorder these.

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +Elide APIs are designed for synchronous request and response behavior. The time allowed to service a synchronous response can be limited by proxy servers and gateways. Analytic queries can often take
typo - "and the delivery the response" - "and the delivery of the response".

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +* Queries can be configured to execute synchronously before switching to asynchronous mode if not finished by a configurable threshold.
If not finished by a client provided threshold.

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +* Status for Queries which may have stopped executing due to an application reboot is also updated.
lowercase q in Queries.

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +* Status for Queries which may have stopped executing due to an application reboot is also updated.
* Status for Queries which may have stopped executing due to an application reboot is also updated.

This is somewhat vague.   What do you mean here?

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +* Historical queries and result stored in the database longer than a configurable threshold are deleted.
Queries and results

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +Elide async API models (AsyncQuery and TableExport) have a simple permission model: Only the principal which submitted a query and admins are allowed to retrieve its status or results.
replace admins with principals which belong to an administrative role.    Also add:
"Principals can be assigned roles when constructing the Elide user object" (with a link around user that points to https://elide.io/pages/guide/v5/03-security.html#user).

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +Elide async API models (AsyncQuery and TableExport) have a simple permission model: Only the principal which submitted a query and admins are allowed to retrieve its status or results.
We should first introduce that the async API is built using Elide models:

"The Async API is built using standard Elide models (AsyncQuery and TableExport).  These models have a simple permission model:..."

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +By default the async API is disabled. The entity models needed to support the Async API are JPA models that are mapped to a specific database schema. This schema must be created in your target databa
Change 2nd sentence to:

The elide models (AsyncQuery and TableExport) needed to support the Async API are JPA models that are mapped to a specific database schema.  Make the models links to the source.

Not sure what to do about the elide-5.x branch link above.  It will be a broken link in a few months.  You could put the correct link off master here for now (even if it is broken).  Also, for long links like this, it is best to use link references in markdown and put the reference definitions at then end of the document.

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +Once you have configured the settings based on your preference, start the Elide service and run the following curl commands to submit calls to JSON-API/GraphQL endpoints be executed asynchronously. D
Same comment about elide-5.x.  These links will all be broken links when we merge elide-5.x to master.

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +* CANCELLED (Only status update to CANCELLED allowed, query cancellation handled by a background process.)
Grammar for cancelled explanation.  We ought to make this a table instead of a list with explanations on the right.

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +Elide has a default implementation of [AsyncQueryDAO](https://github.com/yahoo/elide/blob/elide-5.x/elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryDAO.java) interface which is used
We should start with an explanation of what AsyncQueryDAO is.

Elide async interacts with the persistence layer through an abstraction - the AsyncQueryDAO.  This can be customized by providing your own implementation:

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +Elide has a default implementation of [ResultStorageEngine](https://github.com/yahoo/elide/blob/elide-5.x/elide-async/src/main/java/com/yahoo/elide/async/service/FileResultStorageEngine.java) interfa
Similar comment.  

Table exports leverage a reactive abstraction (ResultStorageEngine) for streaming results to and from a persistence backend.

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/14-swagger.md
> +### Document Size
Let's avoid renaming existing files.  There are too many links that will break and no easy way to validate all of them.  Introduce new files with an appropriate prefix to get the right order.

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +
We should provide a table here (as well as the configuration code samples) with a detailed explanation of each option.

2020-10-30 18:23 UTC, aklish commented on pages/guide/v5/12-asyncapi.md
> +## Security
We should add a design section that explains how the asynchronous API works.  People are more likely to use a feature if they understand in its inner workings.

2020-11-03 17:45 UTC, moizarafat commented on pages/guide/v5/12-asyncapi.md
> +* Status for Queries which may have stopped executing due to an application reboot is also updated.
Updated the statement.

2020-11-03 20:28 UTC, moizarafat commented on pages/guide/v5/12-asyncapi.md
> +By default the async API is disabled. The entity models needed to support the Async API are JPA models that are mapped to a specific database schema. This schema must be created in your target databa
Earlier we discussed bout adding empty links at the bottom of the page. We can not put empty links so I have redirected them to the heading themselves.

2020-11-03 21:56 UTC, moizarafat commented on pages/guide/v5/12-asyncapi.md
> +
Changed to table. The configuration code samples are included in the line below through include tag

2020-11-03 21:56 UTC, moizarafat commented on pages/guide/v5/12-asyncapi.md
> +## Security
Added.

2020-11-04 17:32 UTC, aklish requested changes

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +* Queries and results stored in the database longer than a configurable threshold are deleted.
Change to "Persisted queries and results are deleted after a configurable threshold."

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +* Status for queries which were interrupted due to an application crash/reboot is also updated after restart.
I don't understand this statement.

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +Async requests submitted with the QUEUED status and valid options are queued for execution. Each Elide instance runs a background scheduler process which is responsible for executing these requests i
don't use the word database here - it implies the technology.  Also - don't use the word process - that implies a Unix process or something along those lines.

We should say something like: "Each elide instance runs a scheduler which is responsible for executing requests in background threads.  Upon completion, the background thread posts the query status and results to a persistence store."

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +The Async API is built using standard Elide models (AsyncQuery and TableExport). The results of the requests submitted using AsyncQuery model will be embedded within the `result` property of the mode
This section needs to be broken up into different sections/topics:
- API Models
- Threading
- Async After
- Background Cleaner

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +Each Elide instance also runs two separate background processes for maintenance and cleanup. The first process is responsible for cleaning up of requests and results stored in the database. It is als
Background threads (not processes).  Persistence Store (not database).

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +* JSON
I think we need some explanation how we map results to these formats.

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +* Status for queries which were interrupted due to an application crash/reboot is also updated after restart.
Maybe reword this - "Queries that failed due to an application crash/reboot are automatically flagged as failed upon application restart."

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +The Async API is built using standard Elide models (AsyncQuery and TableExport). The results of the requests submitted using AsyncQuery model will be embedded within the `result` property of the mode
Maybe reword:
"The Async API supports two different query abstractions:
   1. Any read-only API request in JSON-API or GraphQL can be submitted by creating an AsyncQuery object.  After creation, the client can poll the AsyncQuery object asynchronously for status updates.  Once complete, the AsyncQuery object stores the the query result as an embedded attribute.
  2.  For large response bodies, Elide supports a streaming abstraction called TableExport.  It works similarly to the AsyncQuery model but with three important differences:
    1. TableExport can only be leveraged for queries (insert restrictions here).
    1. Upon completion, the TableExport model includes a separate URL attribute which references the query results for streaming downloads.
   2. The results of the GraphQL or JSON-API query are converted into a simple, flat JSON or CSV format."

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +| CANCELLED       | Async request status can be updated to CANCELLED by the users for a background process to perform the cancellation.|
Change description to: "Any running request can be moved to the CANCEL state by the client.  A background thread will release the database resources and mark the request as CANCEL_COMPLETE".

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +There are additional overrides which can be added to update the default configurations related to number of threads, query timeouts and query cleanups.
Change to:

"These additional configuration settings control timeouts and the sizes of thread pools":

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +Once you have configured the settings based on your preference, start the Elide service and run the following curl commands to submit calls to JSON-API/GraphQL endpoints be executed asynchronously. D
Grammar.  Change to:

"After configuring and starting your service, the following commands illustrate how to make asynchronous requests":

2020-11-04 17:32 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +Table exports leverage a reactive abstraction (ResultStorageEngine) for streaming results to and from a persistence backend. This can be customized by proviing your own implementation. Elide provides
proviing - spelling.

2020-11-05 19:08 UTC, moizarafat commented on pages/guide/v5/11.5-asyncapi.md
> +* JSON
We can add the explanation once we have the implementation completed.

2020-11-10 17:11 UTC, aklish requested changes

2020-11-10 17:11 UTC, aklish commented on _data/snippets/v5/async-api-enable.yml
> +  Update your application.yaml with below mentioned additional code.(Only the relevant portions are included.)
Awkward wording.  Change to "Update your application.yaml with the additional code below.  (Only the relevant portions are included.). 

Make this change anywhere you use the same wording.

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +* Queries that interrupted due to an application crash/reboot are automatically flagged as TIMEDOUT.
Queries that are interrupted

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +* Results can be retrieved as an embedded response or URL for downloading later (to be available soon).
Remove available soon for now.  WE'll probably forget to do it later.

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +The Async API supports two different query abstractions, built using standard Elide models (AsyncQuery and TableExport):
remove the comma between abstractions and built.

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +For request submissions and results retrieval, refer the example [calls](/pages/guide/v{{ page.version }}/11.5-asyncapi.html#running).
Change to: "Example API requests and responses can be found here."

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +   * TableExport can only be leveraged for queries where:
I would reword these restrictions like:
TableExport can only be leveraged when:
 1. The query is a simple read.
 2. The model being queried has no relationships.
 3. Only one model is being queried in the request.

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +* Any read-only API request in JSON-API or GraphQL can be submitted by creating an AsyncQuery object. After creation, the client can poll the AsyncQuery object asynchronously for status updates. Once
double `the` in this sentence

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +Each Elide instance runs a scheduler which is responsible for executing these requests in the background threads. Async requests submitted with the QUEUED status and valid options are queued for exec
change "in the background threads" to "in background threads".

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +Each Elide instance runs a scheduler which is responsible for executing these requests in the background threads. Async requests submitted with the QUEUED status and valid options are queued for exec
change "Async requests submitted with the QUEUED status and valid options are queued for execution."  to: "New async requests are initially marked in the QUEUED state."

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +  * The transactions spawned by the async requests which have been executing longer than the configured max run time threshold are terminated. This results in the background thread executing the orig
not sure but run time might be one word.

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +  * The transactions spawned by the async requests which have been executing longer than the configured max run time threshold are terminated. This results in the background thread executing the orig
This is a bit awkward:
"This results in the background thread executing the original request to be interrupted."

I would reword this whole bullet:

"Long running transactions that exceed the runtime threshold are terminated.   Any background thread executing the original request is interrupted."

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +* JSON
Change to "Below are the supported formats for Table Export results:"

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +Below are the different possible statuses of asynchronous calls:
Below are the different states of an asynchronous request:

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +| QUEUED          | Async request is submitted and waiting to be picked up for execution.                 |
Async is implied here.  Why not remove it from the description.

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +| CANCELLED       | Any running request can be moved to the CANCEL state by the client. A background thread will release the resources and mark the request as CANCEL_COMPLETE|
Maybe reword this.  "The client has requested to cancel a running request."

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +| FAILURE         | Async request not completed due to failure encountered by the background process.     |
due to one or more failures.

Change "background process" to "background cleaner".

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +| CANCEL_COMPLETE | Async request has been cancelled by the background process.                           |
Change background process to background cleaner.

2020-11-10 17:11 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +available in the result property of AsyncQuery and TableExport models.
put result in quotes or italics so its known to be an actual attribute label.

2020-11-10 22:00 UTC, moizarafat commented on pages/guide/v5/11.5-asyncapi.md
> +  * The transactions spawned by the async requests which have been executing longer than the configured max run time threshold are terminated. This results in the background thread executing the orig
I believe we should use run time instead of run time cos we are using it to measure the time taken while executing the query. runtime is more appropriate when talking about the runtime environment vs compiletime.

2020-11-13 20:18 UTC, aklish requested changes

2020-11-13 20:18 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +The Async requests can be configured to execute synchronously up to 10 seconds before switching to asynchronous mode. The requests not finished synchronously by the client provided threshold are hand
10 is configurable I assume here.

2020-11-13 20:18 UTC, aklish commented on pages/guide/v5/11.5-asyncapi.md
> +  * The user can at any time update the status of the async requests to CANCELLED. The cleaner polls the AsyncQuery and TableExport models to find any new requests that were CANCELLED and tries to te
Remove "at any time"

2020-11-16 19:12 UTC, aklish approved these changes

2020-11-16 19:12 UTC, merged