Config changes
yahoo/elide-doc pull request #194
Opened 2023-05-30 02:15 UTC by justin-tay

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-05-30 15:11 UTC, aklish commented on _data/snippets/v7/async-api-dao-disabled.yml
> -  ```yaml
We should remove the 
'update your application.yaml' text above.

2023-05-30 15:11 UTC, aklish commented on _data/snippets/v7/async-api-storageengine-disabled.yml
> -  ```yaml
Same comment above.

2023-05-30 15:13 UTC, aklish requested changes
Looks good.  two small comments.

2023-05-31 03:06 UTC, justin-tay commented on _data/snippets/v7/async-api-dao-disabled.yml
> -  ```yaml
Have removed the text.

2023-05-31 03:06 UTC, justin-tay commented on _data/snippets/v7/async-api-storageengine-disabled.yml
> -  ```yaml
Have removed the text.

2023-05-31 03:29 UTC, aklish approved these changes

2023-05-31 03:29 UTC, merged