Changes for configuration, api versioning and exception handling changes
yahoo/elide-doc pull request #198
Opened 2023-10-29 03:52 UTC by justin-tay

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-10-31 23:53 UTC, aklish commented on _data/snippets/v7/exception-mapper.yml
> +      public InvalidEntityBodyExceptionMapper exceptionMapper() {
I wonder if it would be more clear if the return type as an ExceptionMapper here and we add a comment that InvalidEntityBodyExceptionMapper is a developer defined implementation.

2023-10-31 23:57 UTC, aklish commented on pages/guide/v7/09-clientapis.md
> +            .errors(errors -> errors.error(error -> error.message("Invalid entity body")));
The previous example showed how to extend other aspects as well like the code as well as adding custom metadata to the response.  Can we show that as well?

2023-10-31 23:58 UTC, aklish commented on pages/guide/v7/09-clientapis.md
> +The following is the relationship between `ElideError` and `JsonApiError` and `GraphQLError`.
nice

2023-11-01 00:06 UTC, aklish commented on pages/guide/v7/18-migration.md
> +The `ErrorMapper` which mapped an exception to a `CustomErrorException` has been replaced by an `ExceptionMapper` that maps an exception to an `ElideErrorResponse` which contains `ElideErrors` as a b
Maybe explain how JsonApiErrors and GraphQLErrors are what gets serialized in the response as these are also new concepts.

2023-11-01 00:07 UTC, aklish requested changes
Well done.  This is fantastic!

2023-11-02 00:21 UTC, justin-tay commented on _data/snippets/v7/exception-mapper.yml
> +      public InvalidEntityBodyExceptionMapper exceptionMapper() {
Have made the changes to the return type to be the ExceptionMapper.

2023-11-02 00:21 UTC, justin-tay commented on pages/guide/v7/09-clientapis.md
> +            .errors(errors -> errors.error(error -> error.message("Invalid entity body")));
Have made the changes to make the example more complete.

2023-11-02 00:21 UTC, justin-tay commented on pages/guide/v7/18-migration.md
> +The `ErrorMapper` which mapped an exception to a `CustomErrorException` has been replaced by an `ExceptionMapper` that maps an exception to an `ElideErrorResponse` which contains `ElideErrors` as a b
Made the changes to explain the serialization.

2023-11-04 15:37 UTC, aklish approved these changes

2023-11-04 15:37 UTC, merged