Add graph ql docs
yahoo/elide-doc pull request #47
Opened 2017-11-27 17:31 UTC by aklish

Don't merge until elide 4 is released.

2017-11-27 21:39 UTC, DennisMcWherter requested changes

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/09-clientapis.md
> +1.  Most notably, they present a **data model** as an entity relationship graph and **accompanying schema**.
insert: `an` before `accompanying schema`.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/09-clientapis.md
> +* [JSON-API]({{site.baseurl}}/pages/guide/10-jsonapi.html)
idr, but I think we should have a better/more dynamic way of linking to other pages (to avoid broken links in the future if pages are moved). We should investigate.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/10-jsonapi.md
> +Also unlike graphQL, it has no standardized API introspection.  However, Elide adds this capability to any service by exporting
Remove the `Also unlike graphQL`. Also, I'm not sure we're discussing "API" introspection (that's what the spec is for, right?) but instead, we're referring to the data's _schema_.

Would the following be a bit more natural?

`JSON-API has no standardized schema introspection.`

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/10-jsonapi.md
> +Unlike graphQL, it is more structured - laying out how to perform common API operations.
I think we should reword this to be a bit clearer. Maybe expand to something along the lines of this:

```
Unlike graphQL, JSON-API provides a rigorous structure
to its queries; it details the exact behavior of all common
API operations.
```

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/10-jsonapi.md
> +article with a singular author which has a singular address.   While unambiguous, the following is *not* allowed: `/articles/1/author/address`.
Replace the second `with` -> `and`

`article and a singular author which has a singular address`

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/10-jsonapi.md
> +1. The client provides an ID which is replaced by one generated by the data store.  When using _UPSERT_, the client
JSON-API does not have UPSERT.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/10-jsonapi.md
> +When using _UPSERT_, Elide returns object entity bodies (containing newly assigned IDs) in
No UPSERT in JSON-API.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/10-jsonapi.md
> +Elide supports two primary dialects - [RSQL](#rsql) and [basic](#basic).
Remove `basic`. As of Elide 4.x I think we want to deprecate this in favor of RSQL. It is more complicated to use and more limited than RSQL.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/10-jsonapi.md
> +#### Basic Filter Examples
I don't think we want to recommend Basic filtering anymore. We should probably deprecate in Elide 4.0 with plans to remove in 5.0.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/10-jsonapi.md
> +Similar to graphQL:
We should be consistent with our casing of `GraphQL`. http://graphql.org would suggest that `GraphQL` is the appropriate way of casing it instead of `graphQL`. We also use the former casing in the GraphQL document below.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/11-graphql.md
> +Input objects just contain attributes and relationship with names that directly match
Remove `just`.

`match` -> `matching`

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/11-graphql.md
> +Query Objects are more complex given that queries have to support filtering, sorting,
Reword?

```
Query Objects are more complex than Input Objects since they
do more than simply describe data; they must support filtering,
sorting, and pagination.
```

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/11-graphql.md
> +graph. Elide’s GraphQL root documents consists of _relationships_ to these rootable entities.
`consists` -> `consist`.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/11-graphql.md
> +Each relationship is named by its pluralized type name in the GraphQL root document.
`pluralized`? I don't think this is correct.

Each relationship derives its names from the relationship _field name_ which are often pluralized by humans.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/11-graphql.md
> +Every relationship is modeled the same way.  Elide adopts [Relay's pattern for pagination support](http://graphql.org/learn/pagination/).
The way this jumps from the first sentence to the next is a bit confusing to me. I think if we reword the second sentence to something like

`Since Elide adopts ..., relationships are realized as a collection of _edges_ in practice.`

it may be clearer. Basically, at this moment (before continuing) I am confused on how we jumped from discussing our schema structure to Elide's adoption of Relay's pagination pattern.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/11-graphql.md
> +Relationships are a collection of _edges_.  Each edge contains a _node_.  The _node_ is an instance of a
I know what we're trying to explain here since I'm familiar with the system, but these final few sentences are really hard for me to parse for some reason. We should try to rework these.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/11-graphql.md
> +2. The **filter** parameter is used to build complex [RSQL](https://github.com/jirutka/rsql-parser) filter predicates that select zero or more nodes from a relationship.
Remove `complex`?

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/11-graphql.md
> +defaults to a FETCH operation—which simply reads the collection of edges.
Remove `-`

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/11-graphql.md
> +Entity attributes generally do not take arguments. However, attributes can be annotated as computed which allows
Computed attributes with arguments are not yet supported. Slated for 4.1, I believe.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/11-graphql.md
> +All calls must be HTTP `POST` requests made to the root endpoint. This specific endpoint will depend on where you mount the provided servlet.
This is true today, but general comment: we have an option to trivially support `GET` requests in the future if necessary.

2017-11-27 21:39 UTC, DennisMcWherter commented on pages/guide/11-graphql.md
> +### Filtering
This is duplication. We should instead outline these sections and refer to the _specific_ sections for the relevant topics.

If, however, we really want to repeat the information here (I don't have strong opinions on this), we should at least be as DRY as possible for information duplication. We should just have a _single_ source of truth for this information and it should get imported by jekyll here.

2017-11-28 15:53 UTC, aklish commented on pages/guide/09-clientapis.md
> +* [JSON-API]({{site.baseurl}}/pages/guide/10-jsonapi.html)
Agreed.  Had the same thoughts.

2017-11-28 16:06 UTC, aklish commented on pages/guide/11-graphql.md
> +Each relationship is named by its pluralized type name in the GraphQL root document.
I'm only referring to the root document relationships.

2017-11-28 16:13 UTC, aklish commented on pages/guide/11-graphql.md
> +All calls must be HTTP `POST` requests made to the root endpoint. This specific endpoint will depend on where you mount the provided servlet.
We'll document future stuff when it exists I guess.

2017-11-28 16:15 UTC, aklish commented on pages/guide/11-graphql.md
> +### Filtering
Agreed but not sure the best way to fix this now given the new document structure.

2017-11-29 18:57 UTC, wcekan commented on pages/guide/11-graphql.md
> +**REPLACE** can be though of an **UPSERT** followed by an implicit **REMOVE** of everything else that was previously in the collection that the client
can be `thought` of `as` an?

2017-11-29 18:59 UTC, wcekan commented on pages/guide/10-jsonapi.md
> +of boolean expressions.  It is a superset of the [FIQL language](https://tools.ietf.org/html/draft-nottingham-atompub-fiql-00).
Should be capitalized as `Boolean` since it is a name.

2017-11-29 19:00 UTC, wcekan commented on pages/guide/11-graphql.md
> +or 'Sicence Fiction':
`Science`

2017-11-29 19:01 UTC, wcekan commented on pages/guide/11-graphql.md
> +A relationship can be sorted by multiple attributes by seperating the attribute expressions by commas: ','.
separating

2020-05-01 15:56 UTC, closed without merging